# This is a basic workflow to help you get started with Actions

name: DevCard

# Controls when the workflow will run
on:
  push:
    branches: [ master ]
  schedule:
    - cron: "0 0 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.1.0
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
